### ISSUE TITLE
No verification string is displayed after the UTF-8 character is signed.

### ISSUE THREAD

**Issue by TrustHenry** [bpfkorea/keytools#5] opened 2019-06-05 07:35 UTC
Test case:
./bin/keytool sign SCMURBUOY76KQK6MUAIU47XVKJG3H7P5O6HOLVVOOGO57KIJJIHSLE4N "헨리"

Signed message: 38B280A70B76560956D114A6A4E9A6A4BFAC04FA051B8D5B51246A4F2165B8EDEB4F768F8351F765B1E8DCA8391FF37AEF6EB1F8F1BA4EDFB8D9B90B27FE4907ED97A8EBA6AC

./bin/keytool verify GD2MCBTM6JKDU6AONX2RLWG46HQGWBF32OIDVHKF4UCZC2SEBS36FYUM 38B280A70B76560956D114A6A4E9A6A4BFAC04FA051B8D5B51246A4F2165B8EDEB4F768F8351F765B1E8DCA8391FF37AEF6EB1F8F1BA4EDFB8D9B90B27FE4907ED97A8EBA6AC

Result: ED97A8EBA6AC

Result as string is not displayed.

Is it correct that UTF-8 does not support it?

**Comment by Geod24** [comment] 2019-06-05 07:38
Assigned to @AndrejMitrovic

**Closed as completed** 2019-06-05 08:15 UTC

**Comment by Geod24** [comment] 2019-06-05 08:17
@TrustHenry : Can you confirm the issue is fixed ?

**Comment by AndrejMitrovic** [comment] 2019-06-05 08:19
_renames account to **@TrustAndrej**_
